dist: xenial
language: java
services:
  - docker
jdk:
  - openjdk8
before_install:
  - docker pull mysql:5.7.31
  - docker run -d -p 127.0.0.1:3306:3306 --name mysqld
    -e MYSQL_RANDOM_ROOT_PASSWORD=yes -e MYSQL_DATABASE=safetynet -e MYSQL_USER=safetynet -e MYSQL_PASSWORD=safetynet
    mysql:5.7.31 --innodb_log_file_size=256MB --innodb_buffer_pool_size=512MB --max_allowed_packet=16MB --local-infile=1
  - .travis/wait_mysql.sh -u safetynet -psafetynet
script:
  - mvn verify -Dmaven.javadoc.skip=true -B
after_success:
  - bash <(curl -s https://codecov.io/bash)
